
create database cse;

use cse;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    registration_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

insert into users (username, email, password_hash) values ('sbuckner0', 'ypail0@businesswire.com', '$2a$04$KFwIv0urgCsolCHh95RerOqoguTCiDK/eBVYXllg03QLiLBsV0yK2');
insert into users (username, email, password_hash) values ('lmesnard1', 'bpalke1@amazon.co.uk', '$2a$04$uBgxUTIwZtX44hfG0Dn5kuF21fcswuD3/1ii.aOk4cmqQF0t2CWAK');
insert into users (username, email, password_hash) values ('rtoppas2', 'rberrick2@phoca.cz', '$2a$04$9uRy.HbjqLdON9NHWqd2jeLstfbnc5E1SOuy8j4uRg0NLZFOqALzK');
insert into users (username, email, password_hash) values ('lloreit3', 'cchicken3@printfriendly.com', '$2a$04$pG1WLhLwzZPLGN.dYIKMW.SzX96VkCQFkOGP6LA5LigY2ZFEnUziG');
insert into users (username, email, password_hash) values ('drennock4', 'erowesby4@google.com.hk', '$2a$04$pHu0yXIkslqFLAH8tdHXl.3cbraPH/GnDTSv.xYsHtbvjf0FOfET.');
insert into users (username, email, password_hash) values ('dhavenhand5', 'vsteet5@ovh.net', '$2a$04$6S8G/Dkk2Ra4N1MXRIy7aOI8NRbZFJ5fmHLDU9749oP/v0Vk9xuLK');
insert into users (username, email, password_hash) values ('avasey6', 'ddanilchev6@geocities.com', '$2a$04$i4i5iQUfGlg/SX/uaIgsZu7QjOcBR50GFsEhmjYAyR1vi2I1JOYmG');
insert into users (username, email, password_hash) values ('cottewell7', 'cjandera7@chronoengine.com', '$2a$04$uB6Q26rvBWLd4aCfWQxmj.oSZZYQg97DmtUqeAug/2xtrtEaMti6a');
insert into users (username, email, password_hash) values ('nolivari8', 'hmacnockater8@yellowbook.com', '$2a$04$MgzEByOPeyVOfyKqPuWA3.Ens4AnZkMYykwmBA69vwXYYmk42xe42');
insert into users (username, email, password_hash) values ('emeah9', 'equail9@about.com', '$2a$04$XcuUnMid1xCt7d9J6bsvu.5WcabuqvVml5qSCIXEXRFCbP3dkrLKS');
insert into users (username, email, password_hash) values ('mbausa', 'hgwilyma@earthlink.net', '$2a$04$95DT26liSLZq9xFaxT5Hw.ri6m/Vqh5pniTXtxFW4q0QSu2508PFO');
insert into users (username, email, password_hash) values ('kwainerb', 'rmagarrellb@wikipedia.org', '$2a$04$J84e1nYOfa7c/0BC3AJL7.kjT9MnfdoA6gUQLzBgybD8PKBAt6dLm');
insert into users (username, email, password_hash) values ('hscudderc', 'tsmowtonc@dion.ne.jp', '$2a$04$TEPeHP6y91BYSw6baiNQR.l3IJDS6hYMpQ5W1nNURfQZUP8QFwbmW');
insert into users (username, email, password_hash) values ('clapidusd', 'tocloneyd@wunderground.com', '$2a$04$5lwcS4.xpyrrFISSyO76X.iKX5U1b6cYFt/NAE.vwYql32AFL7/4e');
insert into users (username, email, password_hash) values ('hdeavenelle', 'bpechee@51.la', '$2a$04$UWGzief2WeMXgRYAg6WNFug6LDmcUAUskHL8cnrRwMeZqTapYw79W');
insert into users (username, email, password_hash) values ('dfoystonef', 'kmongeotf@nasa.gov', '$2a$04$uSS7L8DWZk0gDi/WBdDYUeTfaejMGgS47GBwMCncBaR7azhyx3e7y');
insert into users (username, email, password_hash) values ('ajaquemeg', 'jbuntong@altervista.org', '$2a$04$5h2KdHsIaYe6vCydUcwM7e5RC/4TJXDirGPnkQ22CBRcOvnnLfMeO');
insert into users (username, email, password_hash) values ('lbirdenh', 'cfountianh@constantcontact.com', '$2a$04$9LK9gi05GHSt3CuM8XDamOhM1g3Ap/AIO1kDQ6LAJVbIcY3veKzzi');
insert into users (username, email, password_hash) values ('fmazilliusi', 'shamelyni@wufoo.com', '$2a$04$U4u85hCpSy8fK9e1FI8AXuBt/cGRriqQfRgKlE/FhmGYFgq47fYou');
insert into users (username, email, password_hash) values ('coruddenj', 'santatj@feedburner.com', '$2a$04$dNOvCiJQTxUiPcOxOZLC/e.N64cD8/dVH3Ghpj.1gUFhmyyU1SdYm');
insert into users (username, email, password_hash) values ('fglencorsek', 'nfairheadk@wp.com', '$2a$04$RDoNAZlUkF4mn2ZW5oVOSei6EOMfulLkxzkUWcQCtafbpaBrfcGey');
insert into users (username, email, password_hash) values ('freidl', 'slagel@cnn.com', '$2a$04$facJHKxnuWdYJNmf1OrRJeIVJM8lo7yRinx3toD4htULiw7u0hwl6');
insert into users (username, email, password_hash) values ('gsteagallm', 'jkondratm@reference.com', '$2a$04$fYfYMm0opeTIYQaqf0QWpOiEUrM5bao/2Nrds7TgS9dcuvIRVCnNy');
insert into users (username, email, password_hash) values ('wgaymern', 'dcamelin@rediff.com', '$2a$04$02TLJce62DkVxHGgj.BhOu4Mo3ngITOSzXYRBkFzl92l6TL8yY0e.');
insert into users (username, email, password_hash) values ('ctrevascuso', 'dharrymano@hexun.com', '$2a$04$2f3XtkXWiZkeQLJ54uRHEO1HT22RyqdLarp10ih41UxeyQ9Ke1Neq');
insert into users (username, email, password_hash) values ('fwallbridgep', 'fbramptonp@last.fm', '$2a$04$NYfvhCYkQxfqf349j5gWj.6aPPRDblo56.rfRcWwmXkJwPpWtPbc.');
insert into users (username, email, password_hash) values ('kballayq', 'lkrienkeq@thetimes.co.uk', '$2a$04$ThGXdM1KUewFunk9PkaCg.ZrXyzXv1hdgSL8QRAujHxo04oR8ZSJ6');
insert into users (username, email, password_hash) values ('vhusseyr', 'davramovichr@prnewswire.com', '$2a$04$fDPaZbvHqhMZBU1vooOPv.MP2ulMfRMwTQg1lYtbcKb2vvvHrva4C');
insert into users (username, email, password_hash) values ('lchaplyns', 'bcopcotts@woothemes.com', '$2a$04$0Uf/0DrVWtx9kwdRWY1uReoq1etEGKxHLwerkQ3dEcTRTyyYn.uBy');
insert into users (username, email, password_hash) values ('jdanslowt', 'baasaft@goo.gl', '$2a$04$eQSkCDsEaa.BaUz8RwVk1eB0rVekJ84qTeJupPtNm036mUhhAsI.S');
insert into users (username, email, password_hash) values ('jgornallu', 'amatthewmanu@diigo.com', '$2a$04$hweZeagrRHus7gudYpiqRuPDBtzUJiTEvz5bLoOw7Vj9gHALgAZ1C');
insert into users (username, email, password_hash) values ('bbrookbankv', 'hloveredgev@spiegel.de', '$2a$04$vS9h4.9CZyvd3JL.wpefWOB.HdFRhXVMPdFsQ3omUL9OP5gPhhpw.');
insert into users (username, email, password_hash) values ('ggoodlifew', 'mtardiffw@chronoengine.com', '$2a$04$V0NoR7T26F0WK6f.dSAwPuunrarO/CV60RHbhlgZOTvJcMZSOoZhW');
insert into users (username, email, password_hash) values ('wedmandsx', 'elittlechildx@163.com', '$2a$04$9Cqunk3n66utymCxa/Yz7e/j7aOKS6JuIHNfrQCJlxoc4HVhspNZq');
insert into users (username, email, password_hash) values ('sbuttreyy', 'rshillabery@goo.gl', '$2a$04$o6dwRLFmchvymel1jjGexuObgi4ZWBE0SSjmJD38ddB.nlZcSL6bC');
insert into users (username, email, password_hash) values ('jmoodeyz', 'lgrindrodz@google.co.uk', '$2a$04$.fOxJJTWOPa/HX9KRmD1mObbIjXWLby5pcxbenpmUt2Xg.f6Ik1N2');
insert into users (username, email, password_hash) values ('kfrichley10', 'olamartine10@mapquest.com', '$2a$04$AW0QD8vywrDBqRSmbheT/eikqpyCTUVUxyv7l4lkZU6Q3ahIolayW');
insert into users (username, email, password_hash) values ('oedmondson11', 'wpenning11@google.de', '$2a$04$tvItoQ7wGcPh3c7u1gxh7.Dt0UcVZnB2jIc6QujxJvtQQSXRPlvGS');
insert into users (username, email, password_hash) values ('fbonavia12', 'bfarmiloe12@blog.com', '$2a$04$0CtdlW8Qg4yYR70U08rSEuZxOOxNNWckH/oZj9szkipOE5J5w2/gK');
insert into users (username, email, password_hash) values ('ldyke13', 'cborzoni13@diigo.com', '$2a$04$4dmM7TuOU.a1Xkiv4JehYOc22IBx06f4a./9NJVJm56fcgNIuFA0.');
insert into users (username, email, password_hash) values ('kkneal14', 'erampley14@google.ca', '$2a$04$KCvborAwQCLMGB1oclrgh.ROIANHSTnEg5JaCLzKXUrJ5.J014HS.');
insert into users (username, email, password_hash) values ('larmytage15', 'dmorston15@parallels.com', '$2a$04$OasdsGUcdtl8LfIn3WTh.OLQi8ETVVGwAL65nTvWUTDFiZFInJgS2');
insert into users (username, email, password_hash) values ('pblodgetts16', 'rmacaulay16@naver.com', '$2a$04$4/EAqWiPIHL7etGIPGUHW.UVS5oRe8qfqyE34iLywSJNjRDlpVs4S');
insert into users (username, email, password_hash) values ('blewsley17', 'jserck17@dmoz.org', '$2a$04$ow5q.vuFmEG4seovpwm1JeOyOkWZKNY03A5AMdttbnCOt4JRgsQqG');
insert into users (username, email, password_hash) values ('tferronier18', 'kcornelleau18@usa.gov', '$2a$04$zKyaSWK1V91sXMVrxiENteL8fk0yMDCvsJgH2Z.AGJQHp6XVP1Dd.');
insert into users (username, email, password_hash) values ('vbarbour19', 'dmacpaden19@state.gov', '$2a$04$qC4B9QzH9nRDdp43NwbtDO5jaJ1OpelLUWXBTzKOntnceYm3JQ9ly');
insert into users (username, email, password_hash) values ('kmcevoy1a', 'mfoyle1a@freewebs.com', '$2a$04$c/E3SyMVYglJbBOKMjYRb.FbM0w2swZbiClbGQkn5ao2uElW3mZwu');
insert into users (username, email, password_hash) values ('estiant1b', 'chalewood1b@disqus.com', '$2a$04$m7okFsIOHvNG1odlWwQ0FuxLnEfWwybX5SEF7mdnG/wPhuUMCp7om');
insert into users (username, email, password_hash) values ('bpickerill1c', 'ckilgour1c@technorati.com', '$2a$04$fFT/3lqbjC5iMiw5aUCDf.sUssYFsuD5OjiEV3T1c.UEjydANZSmW');
insert into users (username, email, password_hash) values ('bcossar1d', 'bbleyman1d@topsy.com', '$2a$04$tMYsp0/hOPNIz00roJ9Mr.dDBClG0LflaNp9/WUVWqAFWIGX4EzRK');
insert into users (username, email, password_hash) values ('jnutton1e', 'droskruge1e@about.com', '$2a$04$6vF/NgUZPRJw.LH/PfV9w.ikNDwy9x.NSBEqSNX9swt1aMkqNxmYa');
insert into users (username, email, password_hash) values ('kdicty1f', 'ssoldan1f@sbwire.com', '$2a$04$.2UNfRTTwfSowc1UzKCqx.vHfi602GFvWRabu60lnGFX9NNuzpzhK');
insert into users (username, email, password_hash) values ('fkrolman1g', 'gabilowitz1g@squidoo.com', '$2a$04$NNTL2vNZZePVkk9QSpB5SeXF3aLlDblHYYqeeLsysNMFeZ5x/Bk/W');
insert into users (username, email, password_hash) values ('kcordel1h', 'bnealy1h@slashdot.org', '$2a$04$ZCKNqJwgpV4mqSRfmH9EveFt7m9.rY1TNOydkhmPXVGzlzErFcuSe');
insert into users (username, email, password_hash) values ('tbasile1i', 'kslaymaker1i@so-net.ne.jp', '$2a$04$LIyQwqBj3cSQWp39fzXyR.d91Vozgc8WfYz1KWi7VsOWcE7QSTD6O');
insert into users (username, email, password_hash) values ('hching1j', 'dskellion1j@nyu.edu', '$2a$04$EfpjsyAXZkAlxNvIGni2Ju8pMAVKfTl4oMTsiSYWM1ijdd1oEGuhC');
insert into users (username, email, password_hash) values ('aklauer1k', 'jservis1k@umich.edu', '$2a$04$qw4LsU5OaQwTVUGmxdgZUuFvIUVXbfHuQkS6fDfcq3cdIyo2kg9LC');
insert into users (username, email, password_hash) values ('kpolgreen1l', 'jbradwell1l@oakley.com', '$2a$04$9H1JW3eMyODAG2PnJzGPgOerqIO0WzQpi60rEDViiqO6QqLZDaxQK');
insert into users (username, email, password_hash) values ('lkelleway1m', 'fromei1m@example.com', '$2a$04$r0XXugm.rZnOc.pk7uyd4OqczmQzJO2Et3QlEkkNTz1Gl/Ot.yd72');
insert into users (username, email, password_hash) values ('rbenzi1n', 'dbartle1n@nature.com', '$2a$04$NLxUnmrXqTcuaqC.vESmrOGlby2htwtkc8C1l7GuFgy669.2Ahkay');
insert into users (username, email, password_hash) values ('sfarnin1o', 'eatthow1o@mediafire.com', '$2a$04$2QW0IGYaIL7sGq4eS3bX0OAIeJ2wkT8MiD2MiCMlnt9JYhwMuX4Y2');
insert into users (username, email, password_hash) values ('mklus1p', 'cmargrie1p@photobucket.com', '$2a$04$ePYQ4IHSxeR4UxGmCj4sQ.OJxu7hFYdEtS16HE5oN1A0.H5n58Y16');
insert into users (username, email, password_hash) values ('rthompstone1q', 'voppery1q@ihg.com', '$2a$04$sukMEzA4kdJUTGpgl6YVVeiBDB6tqpR4wSZdLry0M3m10rcPr4vOq');
insert into users (username, email, password_hash) values ('emcgonagle1r', 'bgraveson1r@clickbank.net', '$2a$04$ljXCElLqwrs5.EjBsLUy4.ZW8wnkJDDjx1DYBCBOE.lWhcEjhVb8e');
insert into users (username, email, password_hash) values ('kcruz1s', 'hrappa1s@theglobeandmail.com', '$2a$04$l/4ajXFxhKji.OtM.idYDueJUa/qk.1Sqn6PdCWIDF4k1ZWwqM9vu');
insert into users (username, email, password_hash) values ('vlammerich1t', 'mwinley1t@oakley.com', '$2a$04$gms3A/87UunVCXC8VWboWuGie9MsXxd4Zs77M6/9PH2owd5bpGRsK');
insert into users (username, email, password_hash) values ('mlaweles1u', 'qcottee1u@oracle.com', '$2a$04$tvwywElGyq7MgHieSDd0U.ooB64m/0kd0WkIGcwx/Xnh7f08qIAwy');
insert into users (username, email, password_hash) values ('ldavage1v', 'ssavile1v@moonfruit.com', '$2a$04$OXm0o9KRONRoiCUPHRl17.pVfgh7OMIzuN5wYy7BtHTdMIAZlHd.G');
insert into users (username, email, password_hash) values ('rkilgour1w', 'deburne1w@cnbc.com', '$2a$04$vvJKJi0Uudf8GErNmsNSJ.vjW793SMApzF4pl/N0t02f90YfdjdZi');
insert into users (username, email, password_hash) values ('bquinnell1x', 'chamal1x@google.es', '$2a$04$KYGvAEqB/gHk8VKUfJJox.ZYVE6aXratMUKiozzu9gdI3e/.U3nTW');
insert into users (username, email, password_hash) values ('smcteer1y', 'wkubas1y@oracle.com', '$2a$04$REk5zadCje2qj04R8fVVbO7QGh3YqMttf8RvTObWCYB1mlkdjcvAC');
insert into users (username, email, password_hash) values ('tbrewers1z', 'lunsworth1z@rakuten.co.jp', '$2a$04$Xm1fnb5QBdEzAu/wSFvgUO3hSRmG3KxdhHTDeNtY18.xKWUbBXVGq');
insert into users (username, email, password_hash) values ('gspiring20', 'afilippov20@deviantart.com', '$2a$04$/kcuvBJ2ZuC940hLoa3qDuDk3ySN031n.ErvYgp8ENLM4u75l4K4C');
insert into users (username, email, password_hash) values ('fgorrick21', 'dhansie21@twitter.com', '$2a$04$yQqYEkrmmRtrt515Rrwwc.F7XF2dMS/u7Uy9SJ9uJbGZ5KuOoKjYC');
insert into users (username, email, password_hash) values ('rbrech22', 'rredsall22@hc360.com', '$2a$04$poAKOvtl/5csMbjJrNrEtu/LKdvVTQ9Mo.jfdAp3nCfsjz4d.t5Xi');
insert into users (username, email, password_hash) values ('dferrarin23', 'ndalliwater23@tumblr.com', '$2a$04$Eogm8P/fzUka7.tAEAYiJ.CYStPybe4Y1DETZVp8LyNnQ.nm5xAOy');
insert into users (username, email, password_hash) values ('vligoe24', 'alello24@nifty.com', '$2a$04$HaOyfP8bw1Z/RZz8pE/E/epDFaJ3S8AXVTTN7ppgNIacsIiTbKJoG');
insert into users (username, email, password_hash) values ('mtorricina25', 'mmaccumiskey25@princeton.edu', '$2a$04$Z2cecnSIU3PjMR/Iee616.HcJX6UeDnsmbwpBhfmWoi8cJk.JM8j.');
insert into users (username, email, password_hash) values ('mpyner26', 'eandrzej26@com.com', '$2a$04$bdy/yKUJSumFLQRl4WONL.d8lfT0.pJvKajrSxBzocaelfUx3qrPe');
insert into users (username, email, password_hash) values ('epedreschi27', 'cdutnall27@google.ca', '$2a$04$l30E0ikowmc2JuIWpu.ObeJriMB1fCK1WdGDaaFeHC5AztnLJLQNm');
insert into users (username, email, password_hash) values ('fleifer28', 'tannand28@mozilla.com', '$2a$04$hDGg.bQlw0dENv18Z83/suOygHHa.yg2sLzAK4VCWcudFQ.aLhkei');
insert into users (username, email, password_hash) values ('jwalaron29', 'dbarthot29@nasa.gov', '$2a$04$arnaORNFW9brK.OdGRmbD.xeT0Kgn2qoVkm8uc6HNcHDsTD/OLVPG');
insert into users (username, email, password_hash) values ('sgasgarth2a', 'gpercy2a@usa.gov', '$2a$04$Z5FKPZajT.yH4ybXwgpaYOLnsutgMMJ1S88gGrEKcuF4FBsSFloB.');
insert into users (username, email, password_hash) values ('rkyrkeman2b', 'mneed2b@tmall.com', '$2a$04$8g/rE56b6sGQuJC4ygzkcuQ0Eo4szNP8mm49OXedDqnkvyGa7wkPi');
insert into users (username, email, password_hash) values ('eglover2c', 'aarnoldi2c@webnode.com', '$2a$04$MyOEoDvjx1dmiCZF1p58oenkvIjB8xXKR3MP4c0koU1S9RXueTQwm');
insert into users (username, email, password_hash) values ('nbranchett2d', 'mheselwood2d@github.com', '$2a$04$UQIeNlNISeMw6VmtCqctj.aIHzzcn7Mg4l0Vx0nvyIwVMzZ0bW3qG');
insert into users (username, email, password_hash) values ('aleathart2e', 'bcampbelldunlop2e@sina.com.cn', '$2a$04$cbeRsffj19u0UM7HjW5MUOacRL2h/UVf853sIsF.m3Bm7XuV73MjO');
insert into users (username, email, password_hash) values ('jwhines2f', 'rbister2f@chron.com', '$2a$04$ny9UesxR0KaXOzL2fpuTMeNPmuNKwqUQQanSlZgFGjn3ssJ.xCh5q');
insert into users (username, email, password_hash) values ('dleed2g', 'mmayoral2g@themeforest.net', '$2a$04$CP/X1lxGiTyJrs3/Hm39BuNGEQ/OMLBrnvy0JwgeCW4JvxQ5MuV82');
insert into users (username, email, password_hash) values ('jadamovitz2h', 'pfoottit2h@last.fm', '$2a$04$fNdsSirTzl/kWEAmmuX80.Rp3PqMPeWLx4RSLfITcDCygGq7QJhRO');
insert into users (username, email, password_hash) values ('eforde2i', 'mlivingstone2i@yolasite.com', '$2a$04$diIYXKSrhQdEo4k7VWF/JuG5Zk3oS/KsG7nUxQuRsQ11ahQrRcxsm');
insert into users (username, email, password_hash) values ('nleece2j', 'bcarff2j@pbs.org', '$2a$04$lLJMqD9cjdgIg8MdIm2F1O1I68k0VrKuSOAKzEbMZUgxy.Z4oCS5O');
insert into users (username, email, password_hash) values ('kbeynon2k', 'bschaumaker2k@ycombinator.com', '$2a$04$TYiVMnvWz40lxhBc0rITq.7xsf7jH6hID5HWIK79bZXVUestT90qa');
insert into users (username, email, password_hash) values ('csayton2l', 'grohmer2l@nymag.com', '$2a$04$zcCaVdZ6Cz2/75lFg7pBdeVToX71eO5R40od8KXZVMp/xunThqnMC');
insert into users (username, email, password_hash) values ('drodder2m', 'mloadwick2m@addthis.com', '$2a$04$QJugogDpW9461EMPCJ6tf.QqA/i/Cv6A5cGRzGx0.CZ/g0Q59UPmm');
insert into users (username, email, password_hash) values ('lslaney2n', 'nbernth2n@macromedia.com', '$2a$04$.ch0ThPyJBNpGwBSfLbyzOz1amat8TgxzCgq0Hp4zuz1VIfgJKCNW');
insert into users (username, email, password_hash) values ('etattersill2o', 'gwhitfield2o@cocolog-nifty.com', '$2a$04$LsnHTaMO9ao5do/ItOkO0.NcHOv7hryDdD7OiFChmMsnezhBghpBS');
insert into users (username, email, password_hash) values ('pceaplen2p', 'ematteuzzi2p@berkeley.edu', '$2a$04$hjC5NhDI/dDCsksi9wnoBOxpBUFAasQY.R6n44ohH9pPhDVSMa1XW');
insert into users (username, email, password_hash) values ('lsoall2q', 'hleah2q@globo.com', '$2a$04$4LBFomKNPAXNUAEkiXucLO8D0LQ7PVXlHzCC0/cKFeM7dc6zFUEi6');
insert into users (username, email, password_hash) values ('imaybery2r', 'groston2r@spotify.com', '$2a$04$wTlPXnoLsp4jrnFSt9WSUezOizttPIsSQg2eeT40w04kAvaAf8r/q');